minor fix - add checks for existing tag

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -60,6 +60,18 @@ jobs:
           echo "SemVer: ${{ env.GitVersion_SemVer }}"
           echo "::notice title=Version::Version is ${{ env.GitVersion_SemVer }}"
 
+      - name: Check if tag already exists
+        id: check
+        run: |
+          TAG_EXISTS=$(git ls-remote --tags origin "refs/tags/${{ env.GitVersion_SemVer }}" | wc -l)
+          echo "exists=$TAG_EXISTS" >> "$GITHUB_OUTPUT"
+          if [[ $TAG_EXISTS -gt 0 ]]; then
+            echo "❌ Tag $GitVersion_SemVer already exists. Failing."
+            exit 1
+          else
+            echo "✅ Tag $GitVersion_SemVer does not exist. Proceeding."
+          fi
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
@@ -75,12 +87,6 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
           ecr: false
-
-      - name: Get short commit SHA
-        id: var
-        run: |
-          calculatedSha="$(git rev-parse --short ${{ github.sha }})"
-          echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT
 
       - name: Docker build
         uses: docker/build-push-action@v6
@@ -115,7 +121,7 @@ jobs:
           docker buildx build --platform "${{ env.PLATFORMS }}" --push -t ${{ env.IMAGE_REPOSITORY }}:${{ env.GitVersion_SemVer }} .
 
       - name: Push tag
-        if: github.ref_name == 'master'
+        if: github.ref_name == 'master' && steps.check.outputs.exists == '0'
         run: |
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
